capstone/capstone/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("recipes.urls"))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

capstone/recipes/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("", views.index, name="index"),
    path("new", views.add_recipe, name="new"),
    path("recipe/<int:recipe_id>", views.recipe_site, name="recipe_site"),
    path("recipe/<int:recipe_id>/edit", views.edit_recipe, name="edit"),
    path("favorites", views.favorites, name="favorites"),
    path("my_recipes", views.my_recipes, name="my_recipes"),

    # API paths
    path("recipes", views.recipe, name="recipe"),
    path("recipes/<int:recipe_id>", views.recipe, name="recipe_put"),
    path("filter/", views.filter_recipes, name="filter")
]

capstone/recipes/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MaxLengthValidator

from .choices import CATEGORIES, ALLERGENS


class User(AbstractUser):
    pass


class Allergen(models.Model):
    name = models.CharField(
        max_length=30, choices=ALLERGENS, blank=True, null=True, default=None, unique=True)

    def serialize(self):
        return {
            "name": self.name(),
            "recipes": [recipe.title for recipe in self.recipes.all()]
        }

    def __str__(self):
        return self.name


class Recipe(models.Model):
    uploader = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="recipes")
    title = models.CharField(
        max_length=100, validators=[MaxLengthValidator(100)])
    image = models.ImageField(upload_to="recipe-images", blank=True, null=True)
    preparation = models.CharField(
        max_length=5000, validators=[MaxLengthValidator(5000)])
    upload_date = models.DateTimeField(auto_now_add=True)
    prep_time = models.IntegerField(blank=True, null=True)
    total_time = models.IntegerField(blank=True, null=True)
    servings = models.IntegerField(blank=True, null=True)
    favorites = models.ManyToManyField(
        User, related_name="favorite_recipes", blank=True)
    category = models.CharField(
        max_length=30, choices=CATEGORIES, default="snacks")
    allergens = models.ManyToManyField(
        Allergen, related_name="recipes", blank=True)

    def serialize(self):
        return {
            "id": self.pk,
            "uploader": self.uploader.username,
            "title": self.title,
            "image": self.image.url if self.image else None,
            "preparation": self.preparation,
            "upload_date": self.upload_date.strftime("%a %H:%M  %y/%m/%d"),
            "ingredients": [ingredient.serialize() for ingredient in self.ingredients.all()],
            "prep_time": self.prep_time,
            "total_time": self.total_time,
            "servings": self.servings,
            "category": self.category,
            "allergens": [allergen.name for allergen in self.allergens.all()]
        }

    def clean(self):
        if not self.uploader or not self.title or not self.category or not self.preparation or not self.upload_date or not self.ingredients or not self.total_time or not self.servings:
            if self.prep_time:
                if self.prep_time > self.total_time:
                    raise ValidationError(
                        "Preparation time cannot be more than total time.")
            raise ValidationError("Recipe data is not correct.")

    def __str__(self):
        return self.title


class Ingredient(models.Model):
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="ingredients")
    name = models.CharField(max_length=100, validators=[
                            MaxLengthValidator(100)])
    quantity = models.CharField(max_length=20)

    def serialize(self):
        return {
            "name": self.name,
            "quantity": self.quantity
        }

    def clean(self):
        if not self.recipe or not self.name or not self.quantity:
            raise ValidationError("Ingredient data is not correct.")

    def __str__(self):
        return f"For: {self.recipe.title} - {self.name}: {self.quantity}"

capstone/recipes/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError, transaction
from django.views.decorators.csrf import csrf_exempt
from django.core.exceptions import ValidationError
from django import forms
from django.core.paginator import Paginator

from .models import User, Recipe, Ingredient, Allergen

from .choices import UNITS, UNITS_METRIC, UNITS_IMPERIAL, ALLERGENS

import json


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ["category"]


# Code copied from project2
def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            if request.POST.get("next"):
                return redirect(request.POST.get("next"))
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "recipes/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        # Redirect user to previously requested page
        if request.GET.get("next"):
            return render(request, "recipes/login.html", {
                "next": request.GET.get("next")
            })
        return render(request, "recipes/login.html")


# Code copied from project2
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


# Code copied from project2
def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # If user tries to register without filling all data
        if not username or not email:
            return render(request, "recipes/register.html", {
                "message": "Please fill out email and username."
            })

        password = request.POST["password"]
        confirmation = request.POST["confirmation"]

        # Ensure password is not an empty string
        if password == "":
            return render(request, "recipes/register.html", {
                "message": "Please fill out password."
            })
        # Ensure password matches confirmation
        if password != confirmation:
            return render(request, "recipes/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "recipes/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "recipes/register.html")


# Home page
def index(request):
    recipes = Recipe.objects.all().order_by("-upload_date")
    favorites = request.user.favorite_recipes.all(
    ) if request.user.is_authenticated else None
    pages = max(1, (recipes.count()/8).__ceil__())

    return render(request, "recipes/list-view.html", {
        "title": "All recipes",
        "recipes": recipes,
        "pages": pages,
        "favorites": favorites,
        "categories": CategoryForm(),
        "allergens": ALLERGENS
    })


# View for creating a new recipe
@login_required
def add_recipe(request):
    return render(request, "recipes/new.html", {
        "title": "Add a new recipe",
        "units": UNITS,
        "units_metric": UNITS_METRIC,
        "units_imperial": UNITS_IMPERIAL,
        "max_characters": Recipe._meta.get_field("preparation").max_length,
        "categories": CategoryForm(),
        "allergens": ALLERGENS
    })


# View for displaying a specific recipe
def recipe_site(request, recipe_id):
    try:
        recipe = Recipe.objects.get(pk=recipe_id)
    except Recipe.DoesNotExist:
        return render(request, "recipes/404.html", {
            "id": recipe_id
        })
    favorites = request.user.favorite_recipes.all(
    ) if request.user.is_authenticated else None
    steps = recipe.preparation.split("-step-")[1:]
    return render(request, "recipes/recipe.html", {
        "recipe": recipe,
        "favorites": favorites,
        "steps": steps,
        "referrer_url": request.META.get("HTTP_REFERER")
    })


# View dor displaying favorite recipes
@login_required
def favorites(request):
    recipes = request.user.favorite_recipes.all().order_by("-upload_date")
    pages = max(1, (recipes.count()/8).__ceil__())

    return render(request, "recipes/list-view.html", {
        "title": "Favorite recipes",
        "recipes": recipes,
        "pages": pages,
        "favorites": recipes,
        "categories": CategoryForm(),
        "allergens": ALLERGENS
    })


# View for displaying the user's own recipes
@login_required
def my_recipes(request):
    recipes = Recipe.objects.filter(
        uploader=request.user).order_by("-upload_date")
    pages = max(1, (recipes.count()/8).__ceil__())

    return render(request, "recipes/list-view.html", {
        "title": "My recipes",
        "recipes": recipes,
        "pages": pages,
        "categories": CategoryForm(),
        "allergens": ALLERGENS
    })


# View for editing a recipe
# Renders the same html as when creating one
@login_required
def edit_recipe(request, recipe_id):
    recipe = Recipe.objects.get(pk=recipe_id)

    if request.POST.get("method") == "edit":
        return render(request, "recipes/new.html", {
            "title": "Edit recipe",
            "recipe": recipe,
            "units": UNITS,
            "units_metric": UNITS_METRIC,
            "units_imperial": UNITS_IMPERIAL,
            "max_characters": Recipe._meta.get_field("preparation").max_length,
            "categories": CategoryForm(),
            "allergens": ALLERGENS
        })
    else:
        redirect = request.POST.get("redirect")
        recipe.delete()
        return HttpResponseRedirect(redirect)


# API endpoint for creating and editing recipes
@csrf_exempt
def recipe(request, recipe_id=None):
    if request.method == "POST":
        data = request.POST
        title = data.get("title")
        preparation = json.loads(data.get("preparation"))
        ingredients = json.loads(data.get("ingredients"))
        prep_time = data.get("preptime")
        total_time = data.get("totaltime")
        servings = data.get("servings")
        category = data.get("category")
        image = request.FILES.get("image")

        # Allergens can be left empty
        try:
            allergens = json.loads(data.get("allergens"))
        except:
            allergens = None

        # No ID means we are creating a new recipe
        if recipe_id == None:
            try:
                # Recipes won't be saved before validating other data
                with transaction.atomic():
                    recipe = Recipe.objects.create(
                        uploader=request.user, title=title, preparation=preparation, category=category,
                        image=image, prep_time=prep_time, total_time=total_time, servings=servings)

                    for ingredient in ingredients:
                        Ingredient.objects.create(
                            recipe=recipe, name=ingredient["name"], quantity=ingredient["quantity"])

                    if allergens is not None:
                        for allergen_name in allergens:
                            # At this point all allergens should have been already created
                            # by running the necessary command, so this is only for safety
                            allergen, _ = Allergen.objects.get_or_create(
                                name=allergen_name)
                            allergen.recipes.add(recipe)
            except ValidationError as e:
                return JsonResponse({"error": str(e)}, status=400)
            return redirect("index")

        # If it's an edit and not a new recipe
        try:
            recipe = Recipe.objects.get(pk=recipe_id)
        except Recipe.DoesNotExist:
            return JsonResponse({"error": "Recipe not found."}, status=404)

        recipe.title = title
        recipe.preparation = preparation
        recipe.prep_time = prep_time
        recipe.total_time = total_time
        recipe.servings = servings
        recipe.category = category
        ingredients = ingredients
        if image:
            recipe.image = image
        else:
            recipe.image.delete(save=True)

        recipe.save()

        # Delete the ingredients for the recipe then add the new ones
        Ingredient.objects.filter(recipe=recipe).delete()
        for ingredient in ingredients:
            Ingredient.objects.create(
                recipe=recipe, name=ingredient["name"], quantity=ingredient["quantity"])

        # Delete the allergens for the recipe then add the new ones
        recipe.allergens.clear()
        if allergens is not None:
            for allergen_name in allergens:
                allergen, _ = Allergen.objects.get_or_create(
                    name=allergen_name)
                allergen.recipes.add(recipe)

        return redirect("my_recipes")

    try:
        recipe = Recipe.objects.get(pk=recipe_id)
    except Recipe.DoesNotExist:
        return JsonResponse({"error": "Recipe not found."}, status=404)

    # Edit only the favorite field of a recipe
    if request.method == "PATCH":
        data = json.loads(request.body)
        favorite = data.get("favorite")

        if favorite is not None:

capstone/recipes/templates/recipes/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}Recipes{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="{% static 'recipes/styles.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">Recipes</a>
        <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'my_recipes' %}">My recipes</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'favorites' %}">Favorites</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'new' %}">Add New Recipe</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
            </li>
            {% endif %}
        </ul>
        <div>
            {% if user.is_authenticated %}
            Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
            Not signed in.
            {% endif %}
        </div>
    </nav>

    <div class="body">
        {% block body %}
        {% endblock %}
    </div>
</body>

</html>

capstone/recipes/templates/recipes/list-view.html
{% extends "recipes/layout.html" %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
<input type="hidden" id="star-empty" value="{% static 'images/star-empty.png' %}">
<input type="hidden" id="star-filled" value="{% static 'images/star-filled.png' %}">
<input type="hidden" id="pages" value="{{ pages }}">
<div id="list-view-main-container">
    <div id="sidebar">
        <button id="btn-sidebar" class="btn"><img src="{% static 'images/search.png' %}" alt="Search"></button>
        <div id="search-container" class="flex column mid-align no-display">
            <input type="text" id="searchbar" placeholder="Search by name">
            <h4>Category</h4>
            {{ categories }}
            <h4>Allergens</h4>
            <div class="flex column start-align">
                {% for allergen in allergens %}
                <div>
                    <input id="{{ allergen.0 }}" type="checkbox" value="{{ allergen.0 }}">
                    <label for="{{ allergen.0 }}">{{ allergen.1 }}</label>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="flex column flex1">
        <div id="list-view-list-container" class="flex flex1">
            {% for recipe in recipes %}
            <div class="recipe-card flex" id="{{ recipe.id }}">
                <a href="{% url 'recipe_site' recipe.pk %}" class="list-view-element">
                    <div class="card">
                        {% if recipe.image %}
                        <img class="card-img-top" src="{{ recipe.image.url }}" alt="Recipe image">
                        {% else %}
                        <img class="card-img-top" src="{% static 'images/meal_big.png' %}" alt="Recipe image">
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.title }}</h5>
                            <p class="card-text"><img src="{% static 'images/time.png' %}" alt="time">{{ recipe.total_time }} mins</p>
                        </div>
                    </div>
                </a>
                {% if user.is_authenticated %}
                {% if request.user != recipe.uploader %}
                <button id="{{ recipe.id }}" class="star">
                    {% if recipe in favorites %}
                    <img src="{% static 'images/star-filled.png' %}" alt="remove">
                    {% else %}
                    <img src="{% static 'images/star-empty.png' %}" alt="add">
                    {% endif %}
                </button>
                {% endif %}
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="flex mid-justify">
            <button id="page-prev" class="btn btn-primary">Previous</button>
            <span id="page-number" class="flex mid-align">Page 1 of {{ pages }}</span>
            <button id="page-next" class="btn btn-primary">Next</button>
        </div>
    </div>
</div>
<script src="{% static 'scripts/utils.js' %}"></script>
<script src="{% static 'scripts/list-view.js' %}"></script>
{% endblock %}

capstone/recipes/templates/recipes/login.html
{% extends "recipes/layout.html" %}

{% block title %}
Log in
{% endblock %}

{% block body %}
<div class="flex column mid-align">
    <h2>Login</h2>

    {% if message %}
    <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post" class="login-form">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        {% if next %}
        <input type="hidden" name="next" value="{{ next }}">
        {% endif %}
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>
</div>
{% endblock %}

capstone/recipes/templates/recipes/my_recipes.html
{% extends "recipes/layout.html" %}

{% block title %}My recipes{% endblock %}

{% block body %}
{% include "recipes/list-view.html" %}
{% endblock %}

capstone/recipes/templates/recipes/new.html
{% extends "recipes/layout.html" %}

{% load static %}

{% block title %}{{ title }}{% endblock %}

{% block body %}
{% if recipe %}
<h1>Edit recipe</h1>
{% else %}
<h1>Add a new recipe</h1>
{% endif %}
<div id="new-main-container">
    {% if recipe %}
    <input id="recipe-id" type="hidden" value="{{ recipe.id }}">
    <input id="steps" type="hidden" value="{{ steps }}">
    {% endif %}
    <div id="new-recipe-container" class="flex column">
        <div id="description-container">
            <div>
                <div class="padding-right width50">
                    <div id="title" class="flex">
                        <div>
                            <h4>Recipe title</h4>
                            <div>
                                <input type="text" maxlength="100" required>
                            </div>
                        </div>
                    </div>
                    <div id="preparation-title">
                        <h4>Preparation</h4>
                        <button id="btn-addstep" class="btn btn-secondary">Add step</button>
                    </div>
                    <div id="new-recipe-description" class="flex column start-align">
                        <textarea id="preparation" class="step" required
                            placeholder=" How do we make this meal? Step 1:"></textarea>
                        <input id="max-characters" type="hidden" value="{{ max_characters }}">
                    </div>
                </div>
                <div class="padding-left width50">
                    <div class="empty-div"></div>
                    <div class="ingredient">
                        <button id="btn-plus" class="btn btn-dark" type="submit"><strong>+</strong></button>
                        <h5>Add an ingredient</h5>
                    </div>
                    <form id="new-ingredient-form" class="ingredient">
                        <label>Name:<input id="ingredient-name" type="text" maxlength="100"></label>
                        <div>
                            <label>Quantity:<input id="ingredient-quantity" type="number" step="0.001" max="999" min="0.001"></label>
                            <select id="ingredient-unit"></select>
                        </div>
                        <input id="units" type="hidden" value="{{ units }}">
                        <input id="metric-units" type="hidden" value="{{ units_metric }}">
                        <input id="imperial-units" type="hidden" value="{{ units_imperial }}">
                        <label><input id="unit-change" type="checkbox">Imperial units</label>
                        <div>
                            <button class="btn btn-secondary" type="reset">Cancel</button>
                            <button class="btn btn-primary" type="submit">Add</button>
                        </div>
                    </form>
                    <div id="ingredients-container" class="flex column">     
                    </div>
                </div>
            </div>
        </div>
        <button id="btn-next" class="btn btn-primary new-button">Next</button>
        <div id="image-container">
            <h2>Upload an image</h2>
            <div class="flex column start-align">
                <div class="flex">
                    <div id="image" class="width50">
                        <img src="{% static 'images/meal_small.png' %}" id="image-preview"></img>
                        <label for="image-upload" class="btn btn-secondary">Select Image</label>
                        <input type="file" id="image-upload" accept="image/*">
                        <button id="btn-clear" class="btn btn-primary">Clear Image</button>
                    </div>
                    <div id="times-container" class="width50">
                        <label>Preparation time (min):<input type="number" id="prep-time" pattern="\d+"></label>
                        <label>Total time to make (min):<input type="number" id="total-time" required></label>
                        <label>Servings:<input type="number" id="servings" required></label>
                        <div id="category">{{ categories }}</div>
                        <div id="allergens">
                            <h4>Select any allergens that this meal might contain (can be left empty)</h4>
                            {% for allergen in allergens %}
                            <label>{{ allergen.1 }}<input type="checkbox" value="{{ allergen.0 }}"></label>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <button id="btn-back" class="btn btn-primary new-button">Back</button>
                <button id="btn-save" class="btn btn-primary">Save</button>
            </div>
        </div>
    </div>
    <div id="toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="mr-auto"></strong>
            <button type="button" class="ml-2 mb-1 close" data-dismiss="toast" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <div class="toast-body">
        </div>
    </div>
</div>
<script src="{% static 'scripts/new.js' %}"></script>
{% endblock %}

capstone/recipes/templates/recipes/recipe.html
{% extends "recipes/layout.html" %}

{% load static %}

{% block title %}{{ recipe.title }}{% endblock %}

{% block body %}
<input type="hidden" id="star-empty"
    value="{% static 'images/star-empty.png' %}">
<input type="hidden" id="star-filled"
    value="{% static 'images/star-filled.png' %}">
<div id="recipe-main-container" class="flex column mid-align">
    <input id="recipe-id" type="hidden" value="{{ recipe.id }}">
    <div class="flex column mid-align">
        <div id="recipe-top-container" class="flex column mid-justify">
            <div>
                <h1>{{ recipe.title }}</h1>
                {% if recipe.uploader == request.user %}
                <div>
                    <div id="options" class="flex mid-align">
                        <img src="{% static 'images/options.png' %}" class="options" alt="Options">
                        <select>
                            <option value="" selected hidden></option>
                            <option value="edit">Edit</option>
                            <option value="delete">Delete</option>
                        </select>
                        <form id="edit" method="post" action="{% url 'edit' recipe.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="method" value="edit">
                        </form>
                        <form id="delete" method="post" action="{% url 'edit' recipe.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="method" value="delete">
                            <input type="hidden" name="redirect" value="{{ referrer_url }}">
                        </form>
                    </div>
                </div>
                {% elif request.user.is_authenticated %}
                <div>
                    <button id="{{ recipe.id }}" class="star">
                        {% if recipe in favorites %}
                        <img src="{% static 'images/star-filled.png' %}" alt="remove">
                        {% else %}
                        <img src="{% static 'images/star-empty.png' %}" alt="add">
                        {% endif %}
                    </button>
                </div>
                {% endif %}
            </div>
            {% if recipe.image %}
            <img src="{{ recipe.image.url }}" alt="{{ recipe.image.name }}">
            {% else %}
            <img src="{% static 'images/meal_big.png' %}" alt="Recipe image placeholder">
            {% endif %}
            <div class="recipe-mobile">
                {% if recipe.prep_time %}
                <p>Preparation time: {{ recipe.prep_time }} minutes</p>
                {% endif %}
                <p>Total time: {{ recipe.total_time }} minutes</p>
            </div>
            <div class="recipe-mobile">
                <p>Servings: <input id="servings" type="number" min="1" max="999" autocomplete="off" value="{{ recipe.servings }}"></p>
                <p class="recipe-list-item">{{ recipe.get_category_display }}</p>
            </div>
            <h2>Ingredients</h2>
            <ul id="recipe-ingredients">
                {% for ingredient in recipe.ingredients.all %}
                <li class="recipe-list-item">
                    <div class="recipe-ingredient-name">{{ ingredient.name }}</div>
                    <div class="recipe-quantity flex column mid-justify">
                        <div>{{ ingredient.quantity }}</div>
                    </div>
                </li>
                {% endfor %}
            </ul>
        </div>
        <div class="left-align">
            <h2>Allergens</h2>
            {% if recipe.allergens.all|length > 0 %}
            <div class="flex wrap">
                {% for allergen in recipe.allergens.all %}
                <div class="allergen-row recipe-list-item">{{ allergen.get_name_display }}</div>
                {% endfor %}
            </div>
            {% else %}
            No allergens listed for this recipe.
            {% endif %}
        </div>
        <div id="preparation-container" class="left-align">
            <h2>Preparation</h2>
            {% if steps|length == 1 %}
            <ul>
                <li>{{steps.0}}</li>
            </ul>
            {% else %}
            <ol>
                {% for step in steps %}
                <li>{{ step }}</li>
                {% endfor %}
            </ol>
            {% endif %}
        </div>
    </div>
    <div class="modal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button id="close" type="button" class="btn btn-secondary" data-dismiss="modal"></button>
                    <button id="proceed" type="button" class="btn btn-primary"></button>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'scripts/utils.js' %}"></script>
<script src="{% static 'scripts/recipe.js' %}"></script>
{% endblock %}